### PR TITLE
[Doc] Add the support information

### PR DESCRIPTION
**Pull request by jerqi**
### What changes were proposed in this pull request?
Add the support information

### Why are the changes needed?
Provide more communication methods for users.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
No need

### CODE REVIEW

**Comment by jerqi** [comment]
企业微信截图_0edbeb97-b811-4cc5-a458-062443cda60a

**Comment by colinmjj** [comment]
I'm not sure for such information, because I haven't seen it in any apache project.
Slack may be a better place for work together

**Comment by jerqi** [comment]
> I'm not sure for such information, because I haven't seen it in any apache project. Slack may be a better place for work together

Flink Remote Shuffle have similar information. Our users are mainly Chinese.

**Review by colinmjj — APPROVED** [review]

**Comment by jerryshao** [comment]
This is not an Apache project, it's OK to leave Tencent specific information and chat group. But we should also suggest user to open issues, which is easy to track.

**Comment by jerqi** [comment]
> This is not an Apache project, it's OK to leave Tencent specific information and chat group. But we should also suggest user to open issues, which is easy to track.
Ok

**Pull request merged**
