### PR TITLE
Fix time unit from micro to mill

### PR DESCRIPTION
**Pull request by colinmjj**
### What changes were proposed in this pull request?
Fix time unit from micro to mill

### Why are the changes needed?
bug fix

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
exist UT

### CODE REVIEW

**Comment by jerqi** [comment]
Why do we need this patch？

**Comment by colinmjj** [comment]
@jerqi The time unit is incorrect, which cause too much check than expected, and too much log is generated
WeChatWorkScreenshot_4064a24c-a1d0-4e4f-8be0-a69d739f548e

**Comment by jerqi** [comment]
Is that  all replaces that need to be fixed?

**Comment by colinmjj** [comment]
> Is that all replaces that need to be fixed?

yes, replace all microSeconds with milliSeconds

**Review by jerqi — APPROVED** [review]

**Pull request merged**
