### PR TITLE
[Build] Only upload logs when test cases are failed

### PR DESCRIPTION
**Pull request by frankliee**
### What changes were proposed in this pull request?
Update CI workflow to upload logs after failures.

### Why are the changes needed?
CI does not upload logs after failures.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Add error cases in UT.

### CODE REVIEW

**Comment by jerqi** [comment]
LGTM, Approve util GA passed.

**Comment by frankliee** [comment]
What is GA ? @jerqi

**Comment by jerqi** [comment]
> What is GA ? @jerqi

Github action.

**Comment by frankliee** [comment]
> LGTM, Approve util GA passed.

**Review by jerqi — APPROVED** [review]

**Pull request merged**
