### PR TITLE
[Improvement] Only initialize the heartbeat thread pool when the role is driver

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?
Only initialize the heartbeat thread pool when the role is driver

### Why are the changes needed?
Just to avoid creating extra thread pool.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
No

### CODE REVIEW

**Comment by jerqi** [comment]
The spark2 also have similar problems. Could you modify the spark2 at the same time?

**Comment by zuston** [comment]
Updated @jerqi .

I'm confused that when heartbeat failed, it will do nothing. Right?

**Comment by colinmjj** [comment]
> Updated @jerqi .
> 
> I'm confused that when heartbeat failed, it will do nothing. Right?

Heartbeat is to notify shuffle server app is alive, and every rpc also will do the notify. According to current implementation, ignore the failed rpc.

**Comment by jerqi** [comment]
If shuffle server haven't received any heartbeat of application, shuffle server will delete the shuffle data of the application.

**Review by jerqi — APPROVED** [review]
LGTM, Thanks for your contribution.

**Pull request merged**
