### PR TITLE
[Feature] Support Spark 3.2

### PR DESCRIPTION
**Pull request by jerqi**
### What changes were proposed in this pull request?
Support Spark 3.2

### Why are the changes needed?
We need support more Spark Versions

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
GA passed （include profiles spark2,spark3,spark3.0,spark3.1,spark3.2）

### CODE REVIEW

**Review by colinmjj — APPROVED** [review]
LGTM, please also backport it to branch-0.2.0

**Comment by colinmjj** [comment]
@jerqi please update readme info about supported spark versions

**Comment by jerqi** [comment]
> @jerqi please update readme info about supported spark versions

OK

**Review by colinmjj — APPROVED** [review]
LGTM

**Pull request merged**
