### PR TITLE
[Improvement] Remove some integration tests under StorageType.HDFS  mode to …

### PR DESCRIPTION
**Pull request by frankliee**
### What changes were proposed in this pull request?
Remove two integration tests under StorageType.HDFS 

### Why are the changes needed?
There are some unnecessary UTs that cost time.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
All existing UTs.

### CODE REVIEW

**Comment by frankliee** [comment]
Do we need to remain  UploadMultiStorage (LOCALFILE_HDFS_2) tests?

**Comment by frankliee** [comment]
Pasted Graphic 2
Pasted Graphic 3

**Reduce about 10 minutes time.**

**Comment by jerqi** [comment]
> Do we need to remain UploadMultiStorage (LOCALFILE_HDFS_2) tests?

We should remove feature and tests at the same time. And if we plan to support streaming application, the feature that server upload shuffle to hdfs useful. But we don't similar plan.

**Comment by colinmjj** [comment]
> Should we remove HDFS StorageType?

@jerqi Yes, storage with HDFS only can't work with task which has small shuffle data segment. And Local_HDFS also can cover HDFS only with proper configuration

**Review by colinmjj — APPROVED** [review]

**Comment by frankliee** [comment]
> > Should we remove HDFS StorageType?
> 
> @jerqi Yes, storage with HDFS only can't work with task which has small shuffle data segment. And Local_HDFS also can cover HDFS only with proper configuration

I will add another PR to totally disable HDFS type.

**Pull request merged**
