### PR TITLE
[Improvement]  Filter the interface address that don't have broadcast address

### PR DESCRIPTION
**Pull request by jerqi**
### What changes were proposed in this pull request?
Filter the interface address that don't have broadcast address

### Why are the changes needed?
Some machines have multiple interface address, but some interface address don't have broadcast address, we can't use it to communicate, so we should filter it.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Manual Test

### CODE REVIEW

**Comment by frankliee** [comment]
Do we need a warning or info log for this situation？

**Comment by jerqi** [comment]
> Do we need a warning or info log for this situation？

I don't think we need. Because it's not warning.

**Comment by colinmjj** [comment]
It's better to add log to show which ip is parsed and which one is used.

**Comment by jerqi** [comment]
> It's better to add log to show which ip is parsed and which one is used.
OK.

**Review by colinmjj — APPROVED** [review]
LGTM

**Pull request merged**
