### PR TITLE
Support using remote fs path to specify the excludeNodesFilePath

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?
Support using remote fs path to specify the excludeNodesFilePath

### Why are the changes needed?
When existing two coordinators serving for online, we hope they can read the consistent exclude nodes file insteading of using the localfile syncing manually.

### Does this PR introduce _any_ user-facing change?
Yes. It's an incompatible change. 

When the default fs is HDFS in the core-site.xml, and the excludeFilePath is specified to "/user/xxxxx" in coordinator server.
After applied this patch, filesystem will be initialized to remote HDFS due to lacking scheme.

### How was this patch tested?
Unit tests.

### CODE REVIEW

**Comment by zuston** [comment]
@jerqi @colinmjj Could u help review?

**Comment by jerqi** [comment]
You seems to use the HDFS as configuration center. I think we should have abstraction `ExcludeNodesConfigProvider`.  We can provide `HdfsExcludeNodesConfigProvider` and `LocalExcludeNodesConfigProvider`. Users can choose one of them. Local file is convenient, and uses don't care consistence sometimes.

**Comment by zuston** [comment]
As we know, Hadoop Filesystem also support reading local file. In this PR, users also can make excludeNodoFilePath as local file path. So the previous unit tests work. refer to: https://github.com/Tencent/Firestorm/blob/6bdf49e1a68131545a8385123da558be287a196f/coordinator/src/test/java/com/tencent/rss/coordinator/SimpleClusterManagerTest.java#L173

But as described in description, it have to specify local file path as `file:/xxxxxx ` ,when using hadoop filesystem reading local file and the default-fs  has been set in the core-site.xml

**Comment by zuston** [comment]
> excludeNodesFile is a workaround solution to do the node management. I think we can have a better way to do it, eg, coordinator support command line/restApi for these management requirement.

As i know, the excludeNodesFile is designed to make shuffle server decommission gracefully. 

Maybe we can make the excludeNodesFile as the one kind of exclude nodes strategy and provide more strategy to exclude node like cli/rest api. Do u think so? @colinmjj 

If we want to preserver the excludeNodesFile, i think this PR is an improvement.

**Comment by zuston** [comment]
Please let me know what u think. Thanks~ @jerqi @colinmjj

**Comment by jerqi** [comment]
For the long term, we prefer to implementing a configuration center and removing the dependency of hadoop's jar. The class `ClientConfManager` in the Coordinator Server also use the method like this pr to manage its conf.  So I think it's ok.@colinmjj WDYT

**Comment by zuston** [comment]
@colinmjj Gentle ping

**Comment by colinmjj** [comment]
OK, we can add this and improve the solution in another PR

**Review by colinmjj — APPROVED** [review]
LGTM

**Comment by zuston** [comment]
Thanks @jerqi @colinmjj

**Pull request merged**
